function Signature = initialiseSignatureStruct()

Signature = struct('timeDelay',[],'pressureAtOneMetre',[],...
    'velocityAtOneMetre',[],'receiverPosition',[],'sourcePosition',[],...
    'souToRecDistance',[],'souToRecAzimuth',[],'souToRecElevation',[]);