function Radiation = initialiseRadiationStruct()

Config = struct('gunIds',[],'duration',[],...
    'sampleRate',[],'waterDensity',[],'waterSoundSpeed',[],...
    'waterTemperature',[],'waterSalinity',[],'bubbleMethod',[],...
    'bubbleFormula',[],'interactionGhost',[]);

Array = struct('gunId',[],'gunPressure',[],...
    'gunGeneratorVolume',[],'gunInjectorVolume',[],...
    'gunInjectorTime',[],'gunRadius',[],...
    'gunX',[],'gunY',[],'gunZ',[]);
    
Signature = initialiseSignatureStruct();

Metrics = initialiseMetricsStruct();

Radiation = struct('Config',Config,'Array',Array,'Signature',Signature,...
    'Metrics',Metrics);