function Bubble = initialiseBubbleStruct()

Config = struct('gunIds',[],'duration',[],'sampleRate',[],'waterDensity',[],...
    'waterSoundSpeed',[],'waterTemperature',[],'waterSalinity',[],...
    'bubbleMethod',[],'bubbleFormula',[],'interactionGhost',[]);

Array = struct('gunId',[],'gunPressure',[],'gunGeneratorVolume',[],...
    'gunInjectorVolume',[],'gunInjectorTime',[],'gunRadius',[],...
    'gunX',[],'gunY',[],'gunZ',[]);

Interactions = initialiseInteractionsStruct();

Calibration = initialiseCalibrationStruct();

Dynamics = struct('gunId',[],'interaction',[],'timeAxis',[],...
    'bubblePressure',[],'bubbleVelocity',[],'bubbleRadius',[],...
    'bubbleEquilibriumRadius',[],'bubbleTemperature',[],'bubbleMass',[],...
    'bubbleEnthalpy',[],'bubbleVolume',[],'bubbleDepth',[],...
    'bubblePressureInternal',[],'bubblePressureAir',[],...
    'bubblePressureVapour',[],'bubblePressureAirGenerator',[],...
    'bubblePressureAirInjector',[],'bubbleMassAir',[],...
    'bubbleMassVapour',[],'bubbleMassAirGenerator',[],...
    'bubbleMassAirInjector',[],'gunPressureGenerator',[],...
    'gunPressureInjector',[],'gunMassAirGenerator',[],...
    'gunMassAirInjector',[],'gunTemperatureGenerator',[],...
    'gunTemperatureInjector',[],'waterDensity',[],'waterSoundSpeed',[],...
    'waterPressure',[]);

Bubble = struct('Config',Config,'Array',Array,'Interactions',Interactions,...
    'Calibration',Calibration,'Dynamics',Dynamics);
