function Plot = initialisePlotStruct()

Plot = struct('inputStatus',[],'souToRecDistance',[],...
    'souToRecAzimuth', [],'souToRecElevation',[],'frequency',[],...
    'radiationFormula',[],'interaction',[],'radiationGhost',[]);