function Metrics = initialiseMetricsStruct()

Metrics = struct('primaryToBubble',[],'bubblePeriod',[],...
    'primaryPeakPositive',[],'primaryPeakNegative',[],...
    'primaryPeakToPeak',[],'primaryPeakPosTime',[],...
    'primaryPeakNegTime',[],'bubblePeakPositive',[],...
    'bubblePeakNegative',[],'bubblePeakToPeak',[],...
    'bubblePeakPosTime',[],'bubblePeakNegTime',[],...
    'signatureRmsBroadband',[],'signatureSelBroadband',[],...
    'signatureRmsBand',[],'signatureSelBand',[],...
    'centralFrequencies',[],'nominalFrequencies',[]);