function Config = initialiseConfigStruct()

Config = struct('inputStatus',[],'Array',[],'gunIds',[],...
    'duration',[],'sampleRate',[],'waterDensity',[],...
    'waterSoundSpeed',[],'waterTemperature',[],'waterSalinity',[],...
    'bubbleMethod',[],'bubbleFormula',[],'interactionGhost',[]);