function Array = initialiseArrayStruct()

Array = struct('inputStatus',[],'gunId',[],'gunPressure',[],...
    'gunGeneratorVolume',[],'gunInjectorVolume',[],'gunInjectorTime',[],...
    'gunRadius',[],'gunX',[],'gunY',[],'gunZ',[]);
